/** Saige natal planet table — owner research only. Do not import from client modules. */
import type { PlanetId } from "../types";
import type { PlanetDef } from "../planets";

export const PLANETS: PlanetDef[] = [
	{
		id: "sun",
		name: "Sun",
		glyph: "Sun",
		lon: 124.23916666666666,
		house: 8,
		wholeSign: 9,
		retrograde: false,
		dignity: "domicile",
		color: "#e6c98a",
		glow: "#c9a15b",
		size: .2,
		radius: 5.35,
		headline: "Royal will. It does not live on a stage. It lives in the vault.",
		why: "She does things because she will not be owned. Pride here is the refusal to be made small.",
		body: [
			"Leo Sun is the need to be the authentic center. In the 8th, the center is a locked room. She wants to walk into a crisis and still have a self left.",
			"This Sun is combusting nothing. Mercury is 27° away — will and mind are separate instruments. She can think about her pride instead of being eaten by it.",
			"Vertex at 6° Leo sits on this Sun. Fated people arrive through the 8th: sex, inheritance, shared resources, the betrayal that splits a life into before and after. She does not date lightly, even when she tells herself she is dating lightly.",
			"Whole Sign puts the Sun in the 9th: meaning, teaching, God. Placidus puts it in the 8th: fusion and the underworld. Lived experience: belief that has been through a death."
		],
		note: "4° Leo 14′ · 8th · domicile · day chart"
	},
	{
		id: "moon",
		name: "Moon",
		glyph: "Moon",
		lon: 27.35 + 3 / 3600 + 210,
		house: 11,
		wholeSign: 12,
		retrograde: false,
		dignity: "fall",
		color: "#d7c4c8",
		glow: "#8b4a62",
		size: .175,
		radius: 5.7,
		headline: "The feeling-body is not comfortable. It is absolute.",
		why: "To protect the bond she has already decided is blood. To never be the fool in the room. To keep a private weather system no one gets to vote on.",
		body: [
			"Moon in Scorpio is already all-or-nothing. In fall, the ordinary lunar functions — soothe, nest, be held, trust the body’s yes — do not work in the factory setting. She cannot get safety from “it’s fine.” She gets safety from I know what this really is.",
			"House 11: this feeling-nature plays out through friends, allies, the future she is aiming at, the internet, the scene. Her people are her home. When a friend lies, it is not a social slight. It is a lunar wound.",
			"Waxing gibbous, ~70% lit, wide applying trine to the Sun. The will and the feeling are not enemies. They are reaching for a trine they have not quite perfected. When they do, she is whole. When they don’t, she performs Leo and feels Scorpio.",
			"Fall does not mean bad Moon. It means the Moon had to learn a foreign country. Comfort will never be her first language. Devotion will."
		],
		note: "27° Scorpio 21′ · 11th · fall · waxing gibbous"
	},
	{
		id: "mercury",
		name: "Mercury",
		glyph: "Merc",
		lon: 151.33666666666667,
		house: 8,
		wholeSign: 10,
		retrograde: false,
		dignity: "exaltation",
		color: "#c5d0c2",
		glow: "#8aa084",
		size: .155,
		radius: 5.15,
		headline: "The gift. The blade that loves the truth of small things.",
		why: "The decision is not real until it has passed this Mercury. If she skips the audit, she pays later.",
		body: [
			"Mercury in Virgo is domicile and exaltation — the strongest traditional planet in the chart. In the 8th it does not gossip. It autopsies. Motives, money under the table, the sentence someone didn’t say, the medical detail, the legal clause, the glitch in the story.",
			"Square to the Moon (4°): feeling versus explaining. She can talk herself out of a true feeling, or feel something she cannot yet word. That square is the stutter between heart and mouth. It is also why writing, naming, diagnosing, and dark humor heal her.",
			"Opposite Uranus in Pisces, plus an almost-exact contraparallel — the sky said it twice. Sudden knowing. Sudden reversal. Cannot be forced into a stupid consensus. Sleep on it and the answer arrives as a jolt, not a committee.",
			"Part of Spirit sits at 1° Virgo, on this Mercury. The soul’s work is this mind, used in the 8th: to tell the truth about what is hidden, and to keep her own soul un-colonized."
		],
		note: "1° Virgo 20′ · 8th · domicile + exaltation"
	},
	{
		id: "venus",
		name: "Venus",
		glyph: "Ven",
		lon: 80.79833333333333,
		house: 6,
		wholeSign: 7,
		retrograde: false,
		dignity: "peregrine",
		color: "#c9d4dc",
		glow: "#8aa3b3",
		size: .185,
		radius: 5.85,
		headline: "The engine. The life actually moves through relating.",
		why: "To be mentally alive with someone, and soul-deep with someone, at the same time. If she can only have one, she will either split herself or leave.",
		body: [
			"This is a locomotive chart. The planet that drives the train is Venus. For all the solar pride and lunar intensity, she does not become herself in a cave. She becomes herself in a bond. Then the cave is inside the bond.",
			"Venus in Gemini: wit, voice, hands, twins. She falls in love with a mind. She stays for the dialogue. Boredom is a moral problem. But this is not a flirtation chart.",
			"Almost exact opposition to Pluto (0°57′, applying). Love is never just love. It is power, fusion, obsession, the fear of being consumed. Lukewarm affection feels like an insult.",
			"Opposite the Ascendant (3°47′) — Venus sits on the descendant. Exact applying sextile to Mars (0°02′). Desire and values agree. Body and taste agree. The sky signed it within two hours of birth.",
			"Mean Lilith at 29° Gemini sits on this descendant. There is a feral feminine in partnership that will not be domesticated. If someone tries to make her “the nice one,” Lilith comes up through the floor."
		],
		note: "20° Gemini 48′ · 6th, pressed to DSC · the engine"
	},
	{
		id: "mars",
		name: "Mars",
		glyph: "Mars",
		lon: 140.83638888888888,
		house: 8,
		wholeSign: 9,
		retrograde: false,
		dignity: "peregrine",
		color: "#c47a64",
		glow: "#a85a46",
		size: .15,
		radius: 5.5,
		headline: "Pride in the fight. Heat in the private.",
		why: "She does not brawl in the street if she can help it. She fights in the bond, in the boardroom behind the boardroom, in the self.",
		body: [
			"Mars in Leo in the 8th: royal anger — “how dare you” — not petty anger. When she is ashamed of that anger, it goes into the 8th and comes out as control, silence, or a sudden clean cut.",
			"Trine Pluto (1.0°) and trine the ASC (3.7°): she can move power without announcing it. Will that works in the dark.",
			"Exact applying sextile to Venus. Desire and taste are one animal. Sextile the MC (1.6°): a Libra midheaven without this heat would be too nice. She is not too nice."
		],
		note: "20° Leo 50′ · 8th · peregrine · direct"
	},
	{
		id: "jupiter",
		name: "Jupiter",
		glyph: "Jup",
		lon: 167.62277777777777,
		house: 9,
		wholeSign: 10,
		retrograde: false,
		dignity: "detriment",
		color: "#cfc6a8",
		glow: "#9a916c",
		size: .17,
		radius: 6.05,
		headline: "Chart ruler in exile. Faith is a craft.",
		why: "She believes what she can do well. She grows by becoming more precise, not more grandiose.",
		body: [
			"Sagittarius rising makes Jupiter the life-ruler. Jupiter wants more, higher, God, luck, the big yes. Virgo says: prove it, fix it, serve it, make it accurate, don’t you dare get sloppy with the sacred.",
			"So her faith is not fireworks. Blessing arrives as a skill, a diagnosis, a humble useful thing — not as a lottery ticket. Detriment is how the power is trained, not a verdict.",
			"9th house: teaching, publishing, far places, law, the search. In Virgo: editor, analyst, technician of meaning, the person who can take a huge idea and make it actually work.",
			"Square Pluto (2.2°): every time she tries to expand, something says who do you think you are? She needs both the preacher and the surgeon. If she only preaches, she gets sloppy. If she only cuts, she forgets why life is worth it."
		],
		note: "17° Virgo 37′ · 9th · detriment · chart ruler"
	},
	{
		id: "saturn",
		name: "Saturn",
		glyph: "Sat",
		lon: 109.18222222222222,
		house: 7,
		wholeSign: 8,
		retrograde: false,
		dignity: "detriment",
		color: "#8a9aa3",
		glow: "#5e7380",
		size: .16,
		radius: 5.25,
		headline: "The spine of her public life. Exact square to the midheaven.",
		why: "Relationships are where she grows up. They are also where she feels the cold. Beginning is a Saturn act.",
		body: [
			"Saturn in Cancer in the 7th: the contract of belonging. Detriment means “be an adult, build the structure” sits in the sign of need. She may parent her partners, or pick partners who parent her, or both, in rotation.",
			"Exact Saturn square MC (orb 0°04′). The vocation is inseparable from who she binds with, whether she takes responsibility, the mother/father story, the fear of being unprofessional and the fear of being unloved.",
			"She cannot fake a public self that her private bonds contradict. If the relationship is chaos, the career feels chaos. If she tries to succeed by abandoning the heart, Saturn in Cancer will tax her. This is not a subplot. This is the plot of the 10th house.",
			"The only cardinal planet in the whole set. She does not start things because she feels like a new beginning. She starts things because a relationship, a duty, or a public weight makes a structure unavoidable."
		],
		note: "19° Cancer 11′ · 7th · detriment · square MC 0°04′"
	},
	{
		id: "uranus",
		name: "Uranus",
		glyph: "Ura",
		lon: 335.99944444444446,
		house: 2,
		wholeSign: 4,
		retrograde: true,
		dignity: "peregrine",
		color: "#8bb8b8",
		glow: "#5a8a8a",
		size: .13,
		radius: 4.85,
		headline: "The floor of her values is rewritten in a dream.",
		why: "You cannot hold Leo pride in a form that never changes.",
		body: ["Uranus in Pisces in the 2nd, retrograde: money, body-worth, what she will and will not sell — will not stay orthodox. The revolution happens inside first. She can look stable while the floor is moving.", "Opposite Mercury (4.7°) and a 0.09° contraparallel. The mind is wired for lightning. Quincunx the Sun (1.8°): identity and upheaval don’t speak the same dialect. Life keeps sending the adjustment."],
		note: "6° Pisces 00′ · 2nd · retrograde"
	},
	{
		id: "neptune",
		name: "Neptune",
		glyph: "Nep",
		lon: 314.26944444444445,
		house: 2,
		wholeSign: 3,
		retrograde: true,
		dignity: "peregrine",
		color: "#7a92ab",
		glow: "#4a6a88",
		size: .13,
		radius: 5,
		headline: "A second, foggy current in worth.",
		why: "Know when the fight is with a ghost.",
		body: ["Neptune in Aquarius in the 2nd, retrograde. Idealism about what she owes the collective. The danger is leaking value — undercharging, overgiving, getting paid in vibes. The gift is a nose for the future’s atmosphere.", "Wide opposition to Mars, trine MC: the public self can carry a vision. The private will can get confused by it. Mars contraparallel Neptune (0.97°) — heat versus fog."],
		note: "14° Aquarius 16′ · 2nd · retrograde"
	},
	{
		id: "pluto",
		name: "Pluto",
		glyph: "Plu",
		lon: 19.85 + 3 / 3600 + 240,
		house: 12,
		wholeSign: 1,
		retrograde: true,
		dignity: "peregrine",
		color: "#b09aa6",
		glow: "#6a4a58",
		size: .145,
		radius: 4.7,
		headline: "The hidden planet on the identity. She is a threshold.",
		why: "Things that look out of proportion to outsiders are correctly sized for a life that includes the invisible.",
		body: [
			"Pluto in Sagittarius in the 12th, retrograde, 4°43′ behind the ascendant. She was born with a secret already in the room. Solitude, sleep, film, hospitals, institutions, the thing in the bloodline that did not get spoken.",
			"Conjunct the ASC from behind: people project power, danger, sex, healing, or “you’re a lot” onto a Sagittarius smile. She will spend years learning that other people’s intensity is often their Pluto, not her job.",
			"Opposite Venus, trine Mars, square Jupiter, sesquare the Sun. The underworld is not a hobby. It is the weather system. The work is not to become less. The work is to give the weather a house."
		],
		note: "19° Sagittarius 51′ · 12th · R · conjunct ASC 4°43′"
	},
	{
		id: "node",
		name: "North Node",
		glyph: "Node",
		lon: 37.01972222222222,
		house: 4,
		wholeSign: 6,
		retrograde: true,
		dignity: "peregrine",
		color: "#d2c6b0",
		glow: "#a09070",
		size: .12,
		radius: 6.25,
		headline: "From proving herself in crisis, to a body that is allowed to stay.",
		why: "Do not make a career out of the underworld just because you are good at it.",
		body: [
			"North Node 7° Taurus in the 4th. South Node 7° Scorpio in the 10th.",
			"From: proving herself through crisis, image, emotional intensity as reputation, being the one who can handle what others can’t, public underworld, control as career.",
			"To: a body, a house, a garden, enoughness, slow worth, a private life that is actually private, food, land, the nervous system coming down.",
			"Saturn quintile the Node (0°10′): fate has a craft. The path is made, not found."
		],
		note: "7° Taurus 01′ · 4th · true node · SN 7° Scorpio 10th"
	},
	{
		id: "chiron",
		name: "Chiron",
		glyph: "Chi",
		lon: 292.6025,
		house: 1,
		wholeSign: 2,
		retrograde: true,
		dignity: "peregrine",
		color: "#b8a898",
		glow: "#7a6a58",
		size: .11,
		radius: 4.45,
		headline: "The wound is not on the front of the house. It is in the wall.",
		why: "I was not finished becoming solid, and I am supposed to already be the adult.",
		body: [
			"Chiron retrograde in intercepted Capricorn in the 1st: shame around competence, status, father, being taken seriously, getting older, being “behind,” needing a credential to deserve to exist.",
			"Because it is intercepted, she may not even name this as the wound. She may think the wound is “I’m too much” (Pluto) or “I feel too hard” (Moon). Under those is Chiron: I must already be solid.",
			"Healing is not become famous and then you’ll feel real. Healing is the slow, unglamorous, Saturn-in-the-best-sense path of building a self that does not have to perform competence in order to deserve rest. The North Node in Taurus 4th is the prescription that matches this wound."
		],
		note: "22° Capricorn 36′ · intercepted 1st · retrograde"
	},
	{
		id: "lilith",
		name: "Lilith",
		glyph: "Lil",
		lon: 29.1 + 29 / 3600 + 60,
		house: 7,
		wholeSign: 7,
		retrograde: false,
		dignity: "peregrine",
		color: "#a89098",
		glow: "#6a4854",
		size: .1,
		radius: 6.4,
		headline: "The feral feminine on the descendant.",
		why: "Do not marry the person who is ashamed of her intensity. Marry the person who is oriented by it.",
		body: ["Mean Lilith at 29° Gemini sits on the descendant with Venus. There is a part of partnership that will not be domesticated.", "True Lilith at 22° Cancer sits with Saturn in the 7th — the untamed need inside the contract of belonging. If someone tries to make her the nice one, this is what comes up through the floor."],
		note: "Mean 29° Gemini 06′ · 7th · on the DSC"
	},
	{
		id: "asc",
		name: "Ascendant",
		glyph: "ASC",
		lon: 24.55 + 57 / 3600 + 240,
		house: 1,
		wholeSign: 1,
		retrograde: false,
		dignity: "angle",
		color: "#efe8dc",
		glow: "#cfc3b0",
		size: .09,
		radius: 6.7,
		headline: "People meet the archer first. They are not meeting the vault.",
		why: "Most people with this rising look like they are easy to know. They are not.",
		body: [
			"24° Sagittarius 34′. Heat, horizon, honesty, a future-tense walk. Chart ruler is Jupiter in Virgo in the 9th — the life-path is not lucky wanderer. It is the craft of meaning.",
			"Pluto sits 4°43′ behind the ascendant in the 12th — the life-force that rose just before she did. People feel her before they have a name for her. The room changes. Animals know. Children know. Liars know.",
			"Mars trines the ASC. Venus opposes it. She is chosen, and she chooses, as a life strategy — not as a hobby."
		],
		note: "24° Sagittarius 34′ · chart face · ruler Jupiter"
	},
	{
		id: "mc",
		name: "Midheaven",
		glyph: "MC",
		lon: 19.25 + 12 / 3600 + 180,
		house: 10,
		wholeSign: 11,
		retrograde: false,
		dignity: "angle",
		color: "#ddd4c6",
		glow: "#b0a494",
		size: .09,
		radius: 6.7,
		headline: "Known for how she handles other people under pressure.",
		why: "She cannot fake a public self that her private bonds contradict.",
		body: [
			"19° Libra 15′. The public story wants harmony, design, law, counsel, the art of the in-between.",
			"Then Saturn squares it exact. The public story is earned in the 7th: partnerships, clients, audience, the other chair.",
			"Venus trine MC, Mars sextile MC, Pluto sextile MC. She can charm, fight, and carry depth — cleanly — if the bond holds."
		],
		note: "19° Libra 15′ · Saturn square 0°04′"
	}
];

export const PLANET_BY_ID: Record<PlanetId, PlanetDef> = PLANETS.reduce(
  (acc, p) => {
    acc[p.id] = p;
    return acc;
  },
  {} as Record<PlanetId, PlanetDef>,
);
